# Generated by Django 5.2.1 on 2025-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Udhiyah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'تم الدفع'), ('booked', 'تم حجز الأضحية'), ('slaughtered', 'تم الذبح'), ('cutting', 'تم التقطيع'), ('half_ready', 'نصف الأضحية جاهز للاستلام'), ('distributing', 'جاري التوزيع'), ('done', 'تم التوزيع')], max_length=50)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
