# Generated by Django 5.2.1 on 2025-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udhiyah',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
